### ISSUE TITLE
Data overflow ?

### ISSUE THREAD

**Issue by PaulCerna** [Noltari/pico-uart-bridge#4] opened 2021-09-08 07:47 UTC
Hello, thanks for this project, it helped me going on my project where I need USB to UART bridge.
One issue I found - when I put a physical loopback on the UART, send a byte buffer of some 100 bytes or so, I receive less bytes back on the USB CDC device. I have now tried the sending in Windows in Python script, and on a dedicated device with native C++ code - in both cases this loopback test looses data.
While I dive into the troubleshooting, do you have any advice on what might be causing this ?
Thanks, Paul.

**Comment by Noltari** [comment] 2021-10-25 16:54
> Hello, thanks for this project, it helped me going on my project where I need USB to UART bridge. One issue I found - when I put a physical loopback on the UART, send a byte buffer of some 100 bytes or so, I receive less bytes back on the USB CDC device. I have now tried the sending in Windows in Python script, and on a dedicated device with native C++ code - in both cases this loopback test looses data. While I dive into the troubleshooting, do you have any advice on what might be causing this ? Thanks, Paul.

Thanks for reporting this.
Could try this commit on the next branch? https://github.com/Noltari/pico-uart-bridge/commit/2460b10523aa3b8537f16f2689c2c051c6de720f
This is the binary generated from the next branch: [pico-uart-bridge.uf2.zip](https://github.com/Noltari/pico-uart-bridge/files/7412210/pico-uart-bridge.uf2.zip)

**Comment by Noltari** [comment] 2022-11-04 12:54
Closing this issue, as I couldn't reproduce it with latest release (https://github.com/Noltari/pico-uart-bridge/releases/tag/v4.0).

**Closed as completed by Noltari** 2022-11-04 12:54 UTC
